<a href="https://colab.research.google.com/github/muammarzainza2000/data-science-2026/blob/main/Pertemuan3_Muammar_Zain_Z_A_240401010304.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from scipy.stats.mstats import winsorize

In [2]:
df = pd.read_csv('housing_dirty.csv')
df.head(5)

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    NaN          1995   Bagus
2   3    249.7       895.0  Depok    NaN          1983    baik
3   4     49.7       178.0    YGY    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  Sedang

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            130 non-null    int64
 1   luas_m2       112 non-null    float64
 2   harga_juta    113 non-null    float64
 3   kota          130 non-null    object
 4   kamar         120 non-null    float64
 5   tahun_bangun  130 non-null    int64
 6   kondisi       130 non-null    object
dtypes: float64(3), int64(2), object(2)
memory usage: 7.2+ KB

In [4]:
df.describe()

               id      luas_m2    harga_juta       kamar  tahun_bangun
count  130.000000   112.000000  1.130000e+02  120.000000    130.000000
mean    65.500000   267.627679  8.856325e+05    3.433333   2062.638462
std     37.671829   885.664181  9.407144e+06    1.776283    701.684043
min      1.000000   -50.000000 -5.000000e+02    1.000000   1890.000000
25%     33.250000    87.050000  3.450000e+02    2.000000   1991.250000
50%     65.500000   193.800000  6.550000e+02    4.000000   2002.000000
75%     97.750000   280.675000  9.550000e+02    5.000000   2011.750000
max    130.000000  9500.000000  1.000000e+08    6.000000   9999.000000

In [5]:
df.isnull().sum()

id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)
print("Data setelah duplikat dihapus: ", df.shape)

Data setelah duplikat dihapus:  (130, 7)

In [7]:
df['kota'] = df['kota'].str.strip().str.title()
df['kondisi'] = df['kondisi'].str.strip().str.lower()
df.head(5)

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  Jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    NaN          1995   bagus
2   3    249.7       895.0  Depok    NaN          1983    baik
3   4     49.7       178.0    Ygy    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  sedang

In [8]:
df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())
df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())
df['kamar'] = df['kamar'].fillna(df['kamar'].median())
df.head(5)

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  Jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    4.0          1995   bagus
2   3    249.7       895.0  Depok    4.0          1983    baik
3   4     49.7       178.0    Ygy    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  sedang

In [10]:
for col in ['harga_juta', 'luas_m2', 'kamar']:
    Q1, Q3 = df[col].quantile([0.25, 0.75])
    IQR = Q3 - Q1
    df[col] = df[col].clip(Q1-1.5*IQR, Q3+1.5*IQR)
df.head(5)

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  Jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    4.0          1995   bagus
2   3    249.7       895.0  Depok    4.0          1983    baik
3   4     49.7       178.0    Ygy    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  sedang

In [11]:
assert df.isnull().sum().sum() == 0, "Masih ada Missing!"
assert df.duplicated().sum() == 0, "Masih ada Duplikat!"
print("Shape akhir: ", df.shape)
df.to_csv('housing_dirty.csv', index=False)
print("Dataset bersih tersimpan!")

Shape akhir:  (130, 7)
Dataset bersih tersimpan!